FROM bastilimbach/docker-magicmirror:raspberry

# manually install dependencies from magic_mirror/modules/*/package.json
#RUN  npm install rpi-dht-sensor@0.1.1 onoff@3.2.2

COPY modules/ /opt/magic_mirror/modules/
